# Generated by Django 3.2.4 on 2021-06-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_drinkmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkmenu',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drinkcategorie', to='website.categorie'),
            preserve_default=False,
        ),
    ]
